# -*- coding: utf-8 -*-
"""videoanalyst_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfouWr2ynPv_7m7Lgv--4yMjMHUiSzAV
"""

# Commented out IPython magic to ensure Python compatibility.
import os
from google.colab import drive
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import matplotlib.pyplot as plt
# %matplotlib inline

drive.mount('/content/drive/')

os.chdir('/content/drive/My Drive/video_analyst/')

ls

pip install -r ./requirements.txt

cd videoanalyst/evaluation/vot_benchmark/pysot/utils/

!python3 setup.py build_ext --inplace

cd ..

!python ./main/test.py --config 'experiments/siamfcpp/test/otb/siamfcpp_googlenet.yaml'

import torch
torch.cuda.is_available()

import zipfile

with zipfile.ZipFile("GOT-10k.zip") as z:
    z.extractall("/content/drive/My Drive/")

ls

!python ./main/train.py --config 'experiments/siamfcpp/train/siamfcpp_googlenet-trn.yaml'



ls

